## Supervised Learning
## Project: House Price Prediction

----
## Exploring the Data
Run the code cell below to load necessary Python libraries and load the kaggle data.

In [1]:
# Import libraries necessary for this project
import numpy as np
import pandas as pd
from time import time
from IPython.display import display # Allows the use of display() for DataFrames
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

# Pretty display for notebooks
%matplotlib inline

# Load the Kaggle dataset
myData = pd.read_csv("FINAL_USO.csv")

# Success - Display the first record
display(myData.head(n=10))
myData.info()
myData.isnull().sum()

,Date,Open,High,Low,Close,Adj Close,Volume,SP_open,SP_high,SP_low,...,GDX_Low,GDX_Close,GDX_Adj Close,GDX_Volume,USO_Open,USO_High,USO_Low,USO_Close,USO_Adj Close,USO_Volume
0,2011-12-15,154.740005,154.949997,151.710007,152.330002,152.330002,21521900,123.029999,123.199997,121.989998,...,51.570000,51.680000,48.973877,20605600,36.900002,36.939999,36.049999,36.130001,36.130001,12616700
1,2011-12-16,154.309998,155.369995,153.899994,155.229996,155.229996,18124300,122.230003,122.949997,121.300003,...,52.040001,52.680000,49.921513,16285400,36.180000,36.500000,35.730000,36.270000,36.270000,12578800
2,2011-12-19,155.479996,155.860001,154.360001,154.869995,154.869995,12547200,122.059998,122.320000,120.029999,...,51.029999,51.169998,48.490578,15120200,36.389999,36.450001,35.930000,36.200001,36.200001,7418200
3,2011-12-20,156.820007,157.429993,156.580002,156.979996,156.979996,9136300,122.180000,124.139999,120.370003,...,52.369999,52.990002,50.215282,11644900,37.299999,37.610001,37.220001,37.560001,37.560001,10041600
4,2011-12-21,156.979996,157.529999,156.130005,157.160004,157.160004,11996100,123.930000,124.360001,122.750000,...,52.419998,52.959999,50.186852,8724300,37.669998,38.240002,37.520000,38.110001,38.110001,10728000
5,2011-12-22,156.350006,156.800003,155.330002,156.039993,156.039993,9888400,124.629997,125.400002,124.230003,...,51.770000,52.400002,49.656178,13179600,38.270000,38.549999,38.209999,38.279999,38.279999,5376800
6,2011-12-23,156.350006,156.490005,155.820007,156.309998,156.309998,3565100,125.669998,126.430000,125.410004,...,52.349998,52.790001,50.169365,4729000,38.470001,38.610001,38.369999,38.490002,38.490002,2162200
7,2011-12-27,155.080002,155.550003,154.539993,154.910004,154.910004,4918600,126.169998,126.820000,126.059998,...,51.680000,51.869999,49.295036,4786400,38.490002,39.209999,38.459999,39.060001,39.060001,7834100
8,2011-12-28,154.050003,154.259995,150.660004,151.029999,151.029999,16436100,126.510002,126.529999,124.730003,...,50.009998,50.060001,47.574883,14170400,38.880001,38.889999,38.189999,38.340000,38.340000,5654300
9,2011-12-29,149.089996,150.720001,148.270004,150.339996,150.339996,19812200,125.239998,126.250000,124.860001,...,49.220001,51.200001,48.658298,12196600,38.389999,38.459999,37.869999,38.410000,38.410000,8924300

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1718 entries, 0 to 1717
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           1718 non-null   object
 1   Open           1718 non-null   float64
 2   High           1718 non-null   float64
 3   Low            1718 non-null   float64
 4   Close          1718 non-null   float64
 5   Adj Close      1718 non-null   float64
 6   Volume         1718 non-null   int64
 7   SP_open        1718 non-null   float64
 8   SP_high        1718 non-null   float64
 9   SP_low         1718 non-null   float64
 10  SP_close       1718 non-null   float64
 11  SP_Ajclose     1718 non-null   float64
 12  SP_volume      1718 non-null   int64
 13  DJ_open        1718 non-null   float64
 14  DJ_high        1718 non-null   float64
 15  DJ_low         1718 non-null   float64
 16  DJ_close       1718 non-null   float64
 17  DJ_Ajclose     1718 non-null   float64
 18  DJ_volume      1718 non-null   int64
 19  EG_open        1718 non-null   float64
 20  EG_high        1718 non-null   float64
 21  EG_low         1718 non-null   float64
 22  EG_close       1718 non-null   float64
 23  EG_Ajclose     1718 non-null   float64
 24  EG_volume      1718 non-null   int64
 25  EU_Price       1718 non-null   float64
 26  EU_open        1718 non-null   float64
 27  EU_high        1718 non-null   float64
 28  EU_low         1718 non-null   float64
 29  EU_Trend       1718 non-null   int64
 30  OF_Price       1718 non-null   float64
 31  OF_Open        1718 non-null   float64
 32  OF_High        1718 non-null   float64
 33  OF_Low         1718 non-null   float64
 34  OF_Volume      1718 non-null   int64
 35  OF_Trend       1718 non-null   int64
 36  OS_Price       1718 non-null   float64
 37  OS_Open        1718 non-null   float64
 38  OS_High        1718 non-null   float64
 39  OS_Low         1718 non-null   float64
 40  OS_Trend       1718 non-null   int64
 41  SF_Price       1718 non-null   int64
 42  SF_Open        1718 non-null   int64
 43  SF_High        1718 non-null   int64
 44  SF_Low         1718 non-null   int64
 45  SF_Volume      1718 non-null   int64
 46  SF_Trend       1718 non-null   int64
 47  USB_Price      1718 non-null   float64
 48  USB_Open       1718 non-null   float64
 49  USB_High       1718 non-null   float64
 50  USB_Low        1718 non-null   float64
 51  USB_Trend      1718 non-null   int64
 52  PLT_Price      1718 non-null   float64
 53  PLT_Open       1718 non-null   float64
 54  PLT_High       1718 non-null   float64
 55  PLT_Low        1718 non-null   float64
 56  PLT_Trend      1718 non-null   int64
 57  PLD_Price      1718 non-null   float64
 58  PLD_Open       1718 non-null   float64
 59  PLD_High       1718 non-null   float64
 60  PLD_Low        1718 non-null   float64
 61  PLD_Trend      1718 non-null   int64
 62  RHO_PRICE      1718 non-null   int64
 63  USDI_Price     1718 non-null   float64
 64  USDI_Open      1718 non-null   float64
 65  USDI_High      1718 non-null   float64
 66  USDI_Low       1718 non-null   float64
 67  USDI_Volume    1718 non-null   int64
 68  USDI_Trend     1718 non-null   int64
 69  GDX_Open       1718 non-null   float64
 70  GDX_High       1718 non-null   float64
 71  GDX_Low        1718 non-null   float64
 72  GDX_Close      1718 non-null   float64
 73  GDX_Adj Close  1718 non-null   float64
 74  GDX_Volume     1718 non-null   int64
 75  USO_Open       1718 non-null   float64
 76  USO_High       1718 non-null   float64
 77  USO_Low        1718 non-null   float64
 78  USO_Close      1718 non-null   float64
 79  USO_Adj Close  1718 non-null   float64
 80  USO_Volume     1718 non-null   int64
dtypes: float64(58), int64(22), object(1)
memory usage: 1.1+ MB

Date             0
Open             0
High             0
Low              0
Close            0
                ..
USO_High         0
USO_Low          0
USO_Close        0
USO_Adj Close    0
USO_Volume       0
Length: 81, dtype: int64

In [2]:
myData.describe()

,Open,High,Low,Close,Adj Close,Volume,SP_open,SP_high,SP_low,SP_close,...,GDX_Low,GDX_Close,GDX_Adj Close,GDX_Volume,USO_Open,USO_High,USO_Low,USO_Close,USO_Adj Close,USO_Volume
count,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000,1.718000e+03,1718.000000,1718.000000,1718.000000,1718.000000,...,1718.000000,1718.000000,1718.000000,1.718000e+03,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000,1.718000e+03
mean,127.323434,127.854237,126.777695,127.319482,127.319482,8.446327e+06,204.490023,205.372637,203.487014,204.491222,...,26.384575,26.715012,25.924624,4.356515e+07,22.113417,22.307148,21.904657,22.109051,22.109051,1.922313e+07
std,17.526993,17.631189,17.396513,17.536269,17.536269,4.920731e+06,43.831928,43.974644,43.618940,43.776999,...,10.490908,10.603110,9.886570,2.909151e+07,11.431056,11.478671,11.373997,11.432787,11.432787,1.575743e+07
min,100.919998,100.989998,100.230003,100.500000,100.500000,1.501600e+06,122.059998,122.320000,120.029999,120.290001,...,12.400000,12.470000,12.269618,4.729000e+06,7.820000,8.030000,7.670000,7.960000,7.960000,1.035100e+06
25%,116.220001,116.540001,115.739998,116.052502,116.052502,5.412925e+06,170.392498,170.962506,169.577499,170.397500,...,20.355000,20.585000,20.180950,2.259968e+07,11.420000,11.500000,11.300000,11.392500,11.392500,6.229500e+06
50%,121.915001,122.325001,121.369999,121.795002,121.795002,7.483900e+06,205.464996,206.459999,204.430000,205.529999,...,22.870001,23.054999,22.677604,3.730465e+07,16.450000,16.635001,16.040000,16.345000,16.345000,1.613015e+07
75%,128.427494,129.087498,127.840001,128.470001,128.470001,1.020795e+07,237.292500,237.722500,236.147503,236.889996,...,26.797500,27.317500,26.478154,5.697055e+07,34.419998,34.667499,34.110000,34.417499,34.417499,2.672375e+07
max,173.199997,174.070007,172.919998,173.610001,173.610001,9.380420e+07,293.089996,293.940002,291.809998,293.579987,...,56.770000,57.470001,54.617039,2.321536e+08,41.599998,42.299999,41.299999,42.009998,42.009998,1.102657e+08

In [ ]:
# We will start out by selecting features gold ETF features
gold_features = ['Open','High', 'Low', 'Volume']
Features = myData[gold_features]
display(Features.head())

target = myData['Adj Close']

# Test Linear Regression Model for small data

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
MyGoldModel = LinearRegression()

#Fit Model
MyGoldModel.fit(Features, Target)

print("Making predicitons for the first 5 entries\n")
print(Features.head())
print("\nThe predictions are:\n")
print(MyGoldModel.predict(Features.head()))
print("\nThe actual values are:\n")
print(target.head())

predicted_adj_close = MyGoldModel.predict(Features.head())
print(mean_absolute_error(target.head(),predicted_adj_close))

As we can predict the Target easly by using inly five main features so we will expand this model and train it completely

In [ ]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler


# Partition data into training and validation groups
X_train, X_test, y_train, y_test = train_test_split(Features, target, random_state = 0)

# Show the results of the split
print("Training set has {} samples.".format(X_train.shape[0]))
print("Testing set has {} samples.".format(X_test.shape[0]))


# Define a new model for training set
gold_model = LinearRegression()
# Fit model
gold_model.fit(X_train, y_train)

#get predicted prices on validation data
val_predictions = gold_model.predict(X_test)
print(mean_absolute_error(y_test,val_predictions))


Final_Model = make_pipeline(StandardScaler(), LinearRegression()).fit(X_train, y_train)

Target = Final_Model.predict(X_test)
print(Target[:10])

RMS = np.sqrt(mean_squared_error(y_test, Target))

yhat = pd.Series(Target, index = y_test.index)

Target.plot.line(label = 'Predicted Value')
y_test.plot.line(label = 'Real Value')
plt.legend()
plt.show()